global_costmap:
  publish_voxel_map: true
  global_frame: odom_combined
  robot_base_frame: base_footprint
  update_frequency: 3.0
  publish_frequency: 1.0
  static_map: false
  rolling_window: true
  width: 40.0   # planning will fail if goal is outside global costmap; 40 m = max goal distance: 20 m
  height: 40.0
  resolution: 0.025
  origin_x: 0.0
  origin_y: 0.0
